### ISSUE TITLE
[PhatLoots] Task #780736 for PhatLoots v5.5.6 generated an exception

### ISSUE THREAD

**Issue by robtbs** [Redned235/PhatLoots#49]
[02:00:01 WARN]: [PhatLoots] Task #780736 for PhatLoots v5.5.6 generated an exception
java.lang.UnsupportedOperationException: null
        at com.google.common.collect.ImmutableCollection.remove(ImmutableCollection.java:278) ~[guava-31.1-jre.jar:?]
        at com.codisimus.plugins.phatloots.regions.WorldGuardRegionHook.getRegionNames(WorldGuardRegionHook.java:40) ~[PhatLoots.jar:?]
        at com.codisimus.plugins.phatloots.listeners.MobListener.getPhatLoot(MobListener.java:135) ~[PhatLoots.jar:?]
        at com.codisimus.plugins.phatloots.listeners.MobSpawnListener.lambda$onMobSpawn$0(MobSpawnListener.java:23) ~[PhatLoots.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by robtbs** [comment]
this happens when someone opens a loot chest

**Comment by Lorias-Jak** [comment]
Got the same exception, were editing the worldguard-region with denizen and removing an member with denizen. Then the exception gets thrown

**Comment by Lorias-Jak** [comment]
After closer examination, we have 2 regions. A parent and a sub-region, both are poly-regions. When we place or remove an Armorstand in the sub-region, WorldGuardRegionHook#getRegionNames is called. Here it comes in the while loop at the regionSet.remove(region) to the error (see picture). I can't quite figure out what the problem is, otherwise I would take care of it and open a PR.

<img width="693" alt="image" src="https://github.com/Redned235/PhatLoots/assets/62625225/faf9f0a1-e5c5-4d56-a4dd-20d5310eb98c">
