### ISSUE TITLE
Random bug

### ISSUE THREAD

**Issue by Banane480** [Redned235/PhatLoots#58]
```
[20:00:26 ERROR]: Error occurred while enabling PhatLoots v5.6.4 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.command.CommandMap org.bukkit.Bukkit.getCommandMap()'
        at com.codisimus.plugins.phatloots.commands.CommandInjector.inject(CommandInjector.java:24) ~[?:?]
        at com.codisimus.plugins.phatloots.commands.CommandHandler.<init>(CommandHandler.java:75) ~[?:?]
        at com.codisimus.plugins.phatloots.PhatLoots.onEnable(PhatLoots.java:184) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.3.5-universal.jar%23307!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[forge-1.20.1-47.3.5-universal.jar%23307!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[forge-1.20.1-47.3.5-universal.jar%23307!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.3.5-universal.jar%23307!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.3.5-universal.jar%23307!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:445) ~[server-1.20.1-20230612.114412-srg.jar%23302!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:345) ~[server-1.20.1-20230612.114412-srg.jar%23302!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:233) ~[server-1.20.1-20230612.114412-srg.jar%23302!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:855) ~[server-1.20.1-20230612.114412-srg.jar%23302!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23302!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

Mohist 1.20.1

**Comment by Redned235** [comment]
PhatLoots only works on Paper or other derivatives. Using modded platforms are unsupported.
